name: twobytwo

channels:

  - conda-forge

  - defaults

dependencies:

  - _libgcc_mutex=0.1=conda_forge

  - _openmp_mutex=4.5=2_gnu

  - ca-certificates=2024.7.4=hbcca054_0

  - ld_impl_linux-64=2.40=hf3520f5_7

  - libffi=3.2.1=he1b5a44_1007

  - libgcc-ng=14.1.0=h77fa898_0

  - libgomp=14.1.0=h77fa898_0

  - libsqlite=3.46.0=hde9e2c9_0

  - libstdcxx-ng=14.1.0=hc0a3c3a_0

  - libzlib=1.2.13=h4ab18f5_6

  - ncurses=6.5=h59595ed_0

  - openssl=1.1.1w=hd590300_0

  - pip=24.0=pyhd8ed1ab_0

  - python=3.8.0=h357f687_5

  - readline=8.2=h8228510_1

  - setuptools=71.0.4=pyhd8ed1ab_0

  - sqlite=3.46.0=h6d4b2fc_0

  - tk=8.6.13=noxft_h4845f30_101

  - wheel=0.43.0=pyhd8ed1ab_1

  - xz=5.2.6=h166bdaf_0

  - zlib=1.2.13=h4ab18f5_6

  - pip:

      - addict==2.4.0

      - aiohttp==3.9.5

      - aiosignal==1.3.1

      - asttokens==2.4.1

      - async-timeout==4.0.3

      - attrs==23.2.0

      - backcall==0.2.0

      - blinker==1.8.2

      - certifi==2024.7.4

      - charset-normalizer==3.3.2

      - click==8.1.7

      - comm==0.2.2

      - configargparse==1.7

      - contourpy==1.1.1

      - cycler==0.12.1

      - dash==2.17.1

      - dash-core-components==2.0.0

      - dash-html-components==2.0.0

      - dash-table==5.0.0

      - decorator==5.1.1

      - docker-pycreds==0.4.0

      - einops==0.8.0

      - executing==2.0.1

      - fastjsonschema==2.20.0

      - filelock==3.15.4

      - flask==3.0.3

      - fonttools==4.53.1

      - freetype-py==2.4.0

      - frozenlist==1.4.1

      - fsspec==2024.6.1

      - fvcore==0.1.5.post20221221

      - gitdb==4.0.11

      - gitpython==3.1.43

      - h5py==3.11.0

      - idna==3.7

      - imageio==2.34.2

      - importlib-metadata==8.2.0

      - importlib-resources==6.4.0

      - iopath==0.1.10

      - ipdb==0.13.13

      - ipython==8.12.3

      - ipywidgets==8.1.3

      - itsdangerous==2.2.0

      - jedi==0.19.1

      - jinja2==3.1.4

      - joblib==1.4.2

      - jsonschema==4.23.0

      - jsonschema-specifications==2023.12.1

      - jupyter-core==5.7.2

      - jupyterlab-widgets==3.0.11

      - kiwisolver==1.4.5

      - lazy-loader==0.4

      - lightning-utilities==0.11.6

      - markupsafe==2.1.5

      - matplotlib==3.7.5

      - matplotlib-inline==0.1.7

      - mesh-to-sdf==0.0.15

      - mpmath==1.3.0

      - multidict==6.0.5

      - nbformat==5.10.4

      - nest-asyncio==1.6.0

      - networkx==3.1

      - ninja==1.11.1.1

      - numpy==1.24.4

      - nvidia-cublas-cu12==12.1.3.1

      - nvidia-cuda-cupti-cu12==12.1.105

      - nvidia-cuda-nvrtc-cu12==12.1.105

      - nvidia-cuda-runtime-cu12==12.1.105

      - nvidia-cudnn-cu12==9.1.0.70

      - nvidia-cufft-cu12==11.0.2.54

      - nvidia-curand-cu12==10.3.2.106

      - nvidia-cusolver-cu12==11.4.5.107

      - nvidia-cusparse-cu12==12.1.0.106

      - nvidia-nccl-cu12==2.20.5

      - nvidia-nvjitlink-cu12==12.5.82

      - nvidia-nvtx-cu12==12.1.105

      - open3d==0.18.0

      - opencv-python

      - packaging==24.1

      - pandas==2.0.3

      - parso==0.8.4

      - pexpect==4.9.0

      - pickleshare==0.7.5

      - pillow==10.4.0

      - pkgutil-resolve-name==1.3.10

      - platformdirs==4.2.2

      - plotly==5.23.0

      - portalocker==2.10.1

      - progressbar==2.5

      - prompt-toolkit==3.0.47

      - protobuf==5.27.2

      - psutil==6.0.0

      - ptyprocess==0.7.0

      - pure-eval==0.2.3

      - pyglet==2.0.16

      - pygments==2.18.0

      - pyopengl==3.1.0

      - pyparsing==3.1.2

      - pyquaternion==0.9.9

      - pyrender==0.1.45

      - python-dateutil==2.9.0.post0

      - pytorch-lightning==2.3.3

      - pytorch3d==0.3.0

      - pytz==2024.1

      - pywavelets==1.4.1

      - pyyaml==6.0.1

      - referencing==0.35.1

      - requests==2.32.3

      - retrying==1.3.4

      - rpds-py==0.19.1

      - scikit-image==0.21.0

      - scikit-learn==1.3.2

      - scipy==1.10.1

      - sentry-sdk==2.11.0

      - setproctitle==1.3.3

      - six==1.16.0

      - smmap==5.0.1

      - stack-data==0.6.3

      - sympy==1.13.1

      - tabulate==0.9.0

      - tenacity==8.5.0

      - termcolor==2.4.0

      - threadpoolctl==3.5.0

      - tifffile==2023.7.10

      - tomli==2.0.1

      - torch==2.4.0

      - torchmetrics==1.4.0.post0

      - torchvision==0.19.0

      - tqdm==4.66.4

      - traitlets==5.14.3

      - transforms3d==0.4.2

      - trimesh==4.4.3

      - triton==3.0.0

      - typing-extensions==4.12.2

      - tzdata==2024.1

      - urllib3==2.2.2

      - wandb==0.17.5

      - wcwidth==0.2.13

      - werkzeug==3.0.3

      - widgetsnbextension==4.0.11

      - yacs==0.1.8

      - yarl==1.9.4

      - zipp==3.19.2

prefix: /localdata/miniconda3/envs/se3
