_wandb:
    value:
        cli_version: 0.17.5
        m:
            - "1": test/epoch/epoch
            - "1": train/network_B/step
            - "1": train/network_B/trans_loss
              "5": 2
              "6":
                - 1
            - "1": train/network_B/total_loss
              "5": 2
              "6":
                - 1
            - "1": train/network_B/rot_loss
              "5": 2
              "6":
                - 1
        python_version: 3.8.0
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 7
                - 16
                - 23
                - 55
            "4": 3.8.0
            "5": 0.17.5
            "8":
                - 5
                - 9
            "12": 0.17.5
            "13": linux-x86_64
cls_data:
    value:
        num_pc_points: 1024
        root_dir: ""
        train_csv_file: ""
        translation: ""
        val_csv_file: ""
cls_model:
    value:
        PCA_obb: false
        corr_module: "No"
        encoder: vn_dgcnn
        num_blocks: 1
        num_heads: 4
        pc_feat_dim: 512
        point_loss: false
        recon_loss: false
data:
    value:
        num_pc_points: 1024
        root_dir: /home/w/PycharmProjects/TwoByTwo-main/data_util/Shape_Data_All_pc
        train_csv_file: /home/w/PycharmProjects/TwoByTwo-main/data_util/Shape_Data_All_pc/stats/Train_all.txt
        translation: ""
        val_csv_file: /home/w/PycharmProjects/TwoByTwo-main/data_util/Shape_Data_All_pc/stats/Test_all.txt
exp:
    value:
        batch_size: 4
        checkpoint_dir: checkpoints
        ckpt_name: ""
        gpus:
            - 0
        load_from: ""
        log_dir: /home/w/two-by-two/logs/network_B
        name: network_B
        num_epochs: 1000
        num_workers: 4
        vis_dir: /home/w/two-by-two/logs/network_B
        weight_file: ""
gpus:
    value:
        - 0
model:
    value:
        aggregator: ""
        corr_feat: "False"
        corr_module: "yes"
        encoder: ""
        encoder_geo: ""
        encoderA: vn_dgcnn
        encoderB: vn_dgcnn
        num_blocks: 1
        num_heads: 4
        pc_feat_dim: 512
        point_loss: true
        pose_predictor_quat: original
        pose_predictor_rot: original
        pose_predictor_trans: original
        recon_loss: false
        sdf_predictor: ""
        transformer_feat_dim: 1024
optimizer:
    value:
        decay_step: 20000
        lr: 0.0001
        lr_clip: 1e-05
        lr_decay: 0
        weight_decay: 1e-06
